---
- hosts: all
  become: true
  tasks:

  - name: Gather machine facts
    ansible.builtin.setup:
      gather_subset:
        - 'machine'
        - 'network'

  - name: Printing some stuff with extra spaces at the end     
    ansible.builtin.debug:
      msg: "Important stuff"   
    