name: Ansible Pull Request Demo
run-name: Steve Tuccio is running code quality checks for ${{ github.sha }} after a push
on: [push]
jobs:
  Ansible-Lint-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run ansible-lint
      uses: ansible/ansible-lint-action@main

